config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'posts#index'
  get 'search_users', to: 'users#search'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users
    resources :posts
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 7

  belongs_to :user
  has_many_attached :images
  has_many :comments

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post
    else
      flash[:alert] = "Something went wrong..."
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    if params[:scope] == 'my_posts'
      @posts = current_user.posts.page(params[:page]).per(7)
    else
      @posts = Post.page(params[:page]).per(7)
    end
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.user == current_user
      @post.destroy
      redirect_to posts_path, notice: 'Post was successfully deleted.'
    else
      redirect_to posts_path, alert: 'You are not authorized to delete this post.'
    end
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, images: [])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @user = User.find_by('email LIKE ?', "%#{params[:email]}%")
    @posts = @user&.posts || []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar  navbar-expand-lg navbar-light bg-light navbar-custom">
  <%= link_to 'Blog', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse container" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span class="user-email">
            <%= current_user.email %>
          </span>
        </li>
        <br>
        <li class="nav-item d-flex align-items-center" style="margin-left: 10%;">
          <%= link_to t('posts.logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item d-flex align-items-center" style="margin-left: 10%;">
          <%= link_to t('posts.signup'), new_user_registration_path, class: 'nav-link' %>
        </li>

        <li class="nav-item d-flex align-items-center" style="margin-left: 10%;">
          <%= link_to t('posts.login'), new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

    <div class="container" style="margin-left: 10%;"  >
      <li>
        <%= link_to "English", locale: 'en' %>
      </li>
      <li>
        <%= link_to "Русский", locale: 'ru' %>
      </li>
    </div>



    <div class="d-flex align-items-center" style="margin-left: 90%;">
      <%= form_with url: search_users_path, method: :get, class: "form-inline my-2 my-lg-0", local: true do %>
        <%= text_field_tag :email, nil, placeholder: t('navbar.search_email'), class: "form-control mr-sm-2" %>
        <%= submit_tag t('navbar.search'), class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </div>

  <div>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <%= link_to t('navbar.new_post'), new_post_path, class: "btn btn-success mb-3" %>
      <% end %>

      <%= link_to t('navbar.all_posts'), posts_path, class: "btn btn-primary mb-3" %>

      <% if user_signed_in? %>
        <%= link_to t('navbar.my_posts'), posts_path(scope: 'my_posts'), class: "btn btn-primary mb-3" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
$("#post_<%= @post.id %>").remove();

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center mb-4">New Post</h1>

      <%= form_for @post, html: { multipart: true, class: 'mb-4' } do |f| %>
        <% if @post.errors.any? %>
          <div class="alert alert-danger error-messages">
            <% @post.errors.full_messages.each do |message| %>
              <%= message %><br>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :images %>
          <%= f.file_field :images, multiple: true, class: 'form-control' %>
        </div>

        <%= f.submit class: 'btn btn-primary btn-block' %>
      <% end %>

      <%= link_to t('post.back'), posts_path, class: 'btn btn-secondary btn-block' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% @posts.each do |post| %>
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post %></h5>
            <p class="card-text"><%= post.description %></p>
            <p class="card-text"><small class="text-muted"> <%= t('post.posted_by') %> <%= post.user.email %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center mb-4">New Post</h1>

      <%= form_for @post, html: { multipart: true, class: 'mb-4' } do |f| %>
        <% if @post.errors.any? %>
          <div class="alert alert-danger error-messages">
            <% @post.errors.full_messages.each do |message| %>
              <%= message %><br>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :images %>
          <%= f.file_field :images, multiple: true, class: 'form-control' %>
        </div>

        <%= f.submit class: 'btn btn-primary btn-block' %>
      <% end %>

      <%= link_to t('post.back'), posts_path, class: 'btn btn-secondary btn-block' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by <%= @post.user.email %></p>

<% @post.images.each do |image| %>
  <%= image_tag(image) %>
<% end %>

<p><%= @post.description %></p>

<% if current_user == @post.user %>
  <%= link_to t('post.edit'), edit_post_path(@post) %> |
<% end %>

<% if user_signed_in? && @post.user == current_user %>
  <%= link_to t('post.delete_post'), @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h2><%= t("post.comments") %></h2>
<% @post.comments.each do |comment| %>
  <p><%= comment.body %></p>
  <p><%= comment.user.email %></p>
  <% if comment.user == current_user %>
    <%= link_to t('post.delete'), post_comment_path(@post, comment), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :body, t('post.new_comment') %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% else %>
  <p>You need to <%= link_to 'sign in', new_user_session_path %> to post a comment.</p>
<% end %>

<%= link_to t('post.back'), posts_path %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/search.html.erb
<h1>Search Results</h1>

<% if @posts.empty? %>
  <p>No posts found for this email.</p>
<% else %>
  <% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= post.description %></p>
  <% end %>
<% end %>

<%= link_to t('post.back'), root_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>